version: "3.9"
services:
  springboot_3.1_fastapi:
    # image: ${IMAGE_NAME}
    build:
      context: .
      args:
        APP_DIR_NAME_SPRINGBOOT: ${APP_DIR_NAME_SPRINGBOOT}
        APP_DIR_NAME_FASTAPI: ${APP_DIR_NAME_FASTAPI}
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
      - 8080:8080
    command: sleep infinity      
  db_mysql_8:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cocolabhub
      MYSQL_LOWER_CASE_TABLE_NAMES: 1
      MYSQL_DATABASE: cocolabhub
      MYSQL_USER: cocolabhub
      MYSQL_PASSWORD: cocolabhub
    ports:
      - "3306:3306"
    volumes:
      - ./init_mysql.sql:/docker-entrypoint-initdb.d/init_mysql.sql
