version: '3.9'
services:
  springboot_3.1.1:
    image: ${IMAGE_NAME_SPRINGBOOT}
    build:
      context: .
      args:
        APP_DIR_NAME: ${APP_DIR_NAME_SPRINGBOOT}      
      dockerfile: ./Dockerfile_springboot
    command: sleep infinity
    ports:
      - "8080:8080"  
  db_mysql_8:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cocolabhub
      MYSQL_LOWER_CASE_TABLE_NAMES: 1      
      MYSQL_DATABASE: cocolabhub
      MYSQL_USER: cocolabhub
      MYSQL_PASSWORD: cocolabhub
    ports:
      - "3306:3306"  
    volumes:
      - ./init_mysql.sql:/docker-entrypoint-initdb.d/init_mysql.sql        
  jupyter_fastapi:
    image: ${IMAGE_NAME_FASTAPI}
    build:
      context: .
      args:
        APP_DIR_NAME_FASTAPI: ${APP_DIR_NAME_FASTAPI}      
      dockerfile: ./Dockerfile_jupyter_fastapi
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - 8888:8888
      - 8000:8000
    depends_on:
      - db_mongodb_7
    command:
      - "jupyter"
      - "lab"
      - "--ip=0.0.0.0"
      - "--port=8888"
      - "--no-browser"
      - "--allow-root"
      - "--NotebookApp.token=''"
      - "--NotebookApp.notebook_dir='/apps'"      
  db_mongodb_7:
    image: mongo:7
    restart: always
    ports:
      - 27017:27017      
