FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y git fonts-nanum && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 작업 디렉토리 설정
WORKDIR /app

ARG APP_DIR_NAME_FASTAPI

# Clone the Git repository. Here we dynamically specify the repository name using the variable defined earlier.
RUN git clone -b data_engineers https://github.com/gocolab/co_templates ${APP_DIR_NAME_FASTAPI}

# Changes the working directory to /app/${REPO_NAME}. This uses the variable to dynamically set the directory path.
WORKDIR /app/${APP_DIR_NAME_FASTAPI}

RUN rm -rf .git